directories:
  output: release
  buildResources: build
appId: com.xtnds.notemaker
productName: NoteMaker
copyright: Copyright © 2026 Arun Raghunathan Seshan
mac:
  target: dmg
  category: public.app-category.productivity
  icon: build/icon.icns
files:
  - filter:
      - dist/**/*
      - main.js
      - preload.js
      - package.json
      - node_modules/**/*
asar: true
electronVersion: 28.3.3
